name: Create GitHub Discussion
description: GitHub Action to create a new GitHub Discussion
inputs:
  title:
    description: |
      The title of the new discussion.
    required: true
  body:
    description: |
      The body of the new discussion.
    required: false
  body-filepath:
    description: |
      The path to a file containing the body of the new discussion (takes precedence over body).
    required: false    
  repository-id:
    description: |
      The ID of a repository in which to create the discussion.
    required: false
  category-id:
    description: |
      The ID of a `DiscussionCategory` within this repository.
    required: false
  repository-name:
    description: |
      The name and owner of the repository in which to create the discussion (e.g., github/octocat).
      If not provided, the action will use the repository that the Action is running in.
    required: false
    default: ${{ github.repository }}
  category-name:
    description: |
      The name of the discussion category in which to create the discussion (defaults to 'General').
    required: false
    default: 'General'
  github-token:
    description: |
      A GitHub token with the necessary permissions to create a discussion.
    required: false
outputs:
  discussion-id:
    description: ID of the created discussion
  discussion-url:
    description: URL of the created discussion   
runs:
  using: node20
  main: dist/index.js
branding:
  icon: message-circle
  color: purple
